version: '2'
services:
  redis-node1:
    image: eason02/redis-instance:3.2
    container_name: redis-node1
    command: redis-server /redis.conf --port 6379 --maxmemory-policy allkeys-lru
    #network_mode: host
    ports:
      - 6379:6379
      - 16379:16379
    volumes:
      - ./redis-instances/6379/data:/data
  redis-node2:
    image: eason02/redis-instance:3.2
    container_name: redis-node2
    command: redis-server /redis.conf --port 6380 --maxmemory-policy allkeys-lru
    #network_mode: host
    ports:
      - 6380:6380
      - 16380:16380
    volumes:
      - ./redis-instances/6380/data:/data
  redis-node3:
    image: eason02/redis-instance:3.2
    container_name: redis-node3
    command: redis-server /redis.conf --port 6381 --maxmemory-policy allkeys-lru
    #network_mode: host
    ports:
      - 6381:6381
      - 16381:16381
    volumes:
      - ./redis-instances/6381/data:/data
  redis-node4:
    image: eason02/redis-instance:3.2
    container_name: redis-node4
    command: redis-server /redis.conf --port 6382 --maxmemory-policy allkeys-lru
    #network_mode: host
    ports:
      - 6382:6382
      - 16382:16382
    volumes:
      - ./redis-instances/6382/data:/data
  redis-node5:
    image: eason02/redis-instance:3.2
    container_name: redis-node5
    command: redis-server /redis.conf --port 6383 --maxmemory-policy allkeys-lru
    #network_mode: host
    ports:
      - 6383:6383
      - 16383:16383
    volumes:
      - ./redis-instances/6383/data:/data
  redis-node6:
    image: eason02/redis-instance:3.2
    container_name: redis-node6
    command: redis-server /redis.conf --port 6384 --maxmemory-policy allkeys-lru
    #network_mode: host
    ports:
      - 6384:6384
      - 16384:16384
    volumes:
      - ./redis-instances/6384/data:/data
