#!/bin/bash

# Description: FastOperation script written by Eason Lau<eason.lau02@hotmail.com>
# Date: 2018-08

source ./var.ini

env=$(bosh envs | awk 'NR=1 {print $2}')
if [ -n $env ]; then
	echo -e "ENV : $b$env$e"
	bosh -e $env deps | awk '/^[a-zA-Z]/ {print ++x" : "$1}'
fi
